### PR TITLE
B23user logout

### PR DESCRIPTION
**Pull request by loragardner**
go ahead

### CODE REVIEW

**Comment by loragardner** [comment]
go ahead

**Review by jpopovic84 — APPROVED** [review]

**Review by jpopovic84 — APPROVED** [review]

**Comment by NemoMilosevic** [comment]
deleted the conflict and approved

**Review by YuliiaMashkina — APPROVED** [review]
approving, looks good

**Review by YuliiaMashkina — APPROVED** [review]
Should i approve twice?

**Pull request merged**
