### PR TITLE
Login func.

### PR DESCRIPTION
**Pull request by jpopovic84**
Login func.

### CODE REVIEW

**Review by AnastasiiaMikharieva — COMMENTED** [review]
Great code!

**Comment by jpopovic84** [comment]
please, review my code

**Comment by jpopovic84** [comment]
Can you, please approve the code, and merge it?

**Review by walid01994 — APPROVED** [review]
nice

**Comment by jpopovic84** [comment]
Thank You

**Comment by walid01994** [comment]
you are welcome

**Pull request merged**
