### PR TITLE
Walid tc250

### PR DESCRIPTION
**Pull request by walid01994**
added some code

### CODE REVIEW

**Review by jpopovic84 — COMMENTED** [review]
Hi there !!

**Comment by walid01994** [comment]
Hey, how's my code looking! lol

**Comment by NemoMilosevic** [comment]
hey your code looks awesome!

**Comment by jpopovic84** [comment]
I like your approach !!

**Review by jpopovic84 — APPROVED** [review]
Good job !!!

**Review by Rodgersouko — COMMENTED** [review]
good work

**Pull request merged**
